disabled-metrics:
  minecraft:mined: true
  minecraft:killed: true
  minecraft:picked_up: true
  minecraft:dropped: true
  minecraft:used: true
  minecraft:broken: true
  minecraft:crafted: true
  minecraft:custom: true